### ISSUE TITLE
In numbered list unneeded newline after item number

### ISSUE THREAD

**Issue by crystalfp** [nea/MarkdownViewerPlusPlus#47]
Rendering a simple numbered list with a blank line between items gives (on screen and in pdf but not in html) an unwanted newline after the item number (see first screen capture below). Instead, without blank line gives the correct list rendering (see second screen capture below).
Bug or feature?
Thanks for looking!
mario

![capture1](https://user-images.githubusercontent.com/865866/31116170-59a41bc6-a825-11e7-940e-4557840e5d40.png)
![capture2](https://user-images.githubusercontent.com/865866/31116173-5cfc7520-a825-11e7-8fd9-8a4586969392.png)

**Comment by nea** [comment]
Hey @crystalfp 

You are not the first seeing this issue but it is not affecting everyone. I have one colleague seeing the same, another facing no issues, same as me.

I will have to put some time into this.


Sorry

**Comment by DavidBruchmann** [comment]
When exported to HTML the fault is not visible, but when exported to PDF.
In HTML it still could be influenced easily by CSS anyway ...
Just tested with the x86 Version on 64b-Windows-7, UTF-8 and different line-breaks (CR, LF, CR LF).

**Comment by DavidBruchmann** [comment]
Example-Image with "display all characters" shows that after the list there is an issue too.  

![screenshot_md_notepad](https://user-images.githubusercontent.com/999146/31175502-a5ccf35a-a939-11e7-9523-a68f84f6802b.png)

**Comment by nea** [comment]
Hi @DavidBruchmann 

What do you mean with "after the list is an issue"? If you mean that there is no line break: that is by CommonMark specification and standard. After a list, two spaces are not enough to line break but only a complete new line to result in a spacing between list and new line.


Best

**Comment by DavidBruchmann** [comment]
If I'm not wrong the list should end before line three because lines 3 and 4 are not indented.

**Comment by nea** [comment]
Hi @DavidBruchmann 

As you can check yourself, it doesn't depend on line indentation in this case but real line breaks. You can test it yourself here: http://spec.commonmark.org/dingus/?text=-%20a%0A-%20b%0A%0A%20%20%5Bref%5D%3A%20%2Furl%0A-%20d%0A

This is an example based on the implemented spec 0.27.


Best

**Comment by Stevoisiak** [comment]
I've encountered a similar issue when adding lists and refrence-styled URLs.
#57

**Comment by nkaleidoskop** [comment]
I also consistently see this bug whenever there are two lists separated by a blank line.
```
* foo
* bar

* cat
```
Creating a non-list-line between the lists prevents the bug.

Surprisingly, the following will _not_ trigger the bug (note the different bullet point):
```
* foo
* bar

- cat
```
Hope this helps with finding the bug!

**Comment by nea** [comment]
Hi @crystalfp, @Stevoisiak 

I just released a new version [0.8.0](https://github.com/nea/MarkdownViewerPlusPlus/releases/tag/0.8.0). 

Could you please check if this issue still occurs?


Thanks a lot

**Comment by crystalfp** [comment]
Seems fixed in 0.8.0 **but only** if you do not leave an empty line between list entries.
Here is an example:
```
Approfondiamo.

1. Vi ho trovato paralleli.

2. Ho visto i risultati.

3. C'è il mio interesse.

Voglio provare.

- 001 piano

- 002 la premessa

- 003 questi paralleli

```
If you remove the empty lines between the list items the rendering is perfect.

**Comment by nea** [comment]
Hey @crystalfp and thanks for cheking

Please refer to https://github.com/nea/MarkdownViewerPlusPlus/issues/39#issuecomment-305716146 why this happens because of the loose lists.


Thanks

**Comment by Stevoisiak** [comment]
@nea The spacing bug still occurs in 0.8.1 if a code-block is inserted after a list item.

**Sample .MD file**

```
- List item followed by code block

		print("Hello, world!")
```

**Appearance on GitHub**

- List item followed by code block

		print("Hello, world!")

**Appearance in MarkdownViewer++**

![MarkdownViewer++: Spacing bug with bulleted list and code block](https://user-images.githubusercontent.com/1330770/37038372-9b7418c8-2122-11e8-8c03-e1ec91be267b.png)

**Comment by nea** [comment]
Hi @Stevoisiak 

It is a loose list why this behaviour occurs. I haven't changed or fixed anything in this regard as it mainly works as implemented but not as expected ^^


Best

**Comment by Stevoisiak** [comment]
@nea Should I open a separate issue report for this?

**Comment by nea** [comment]
Hi @Stevoisiak 

You can but this is nothing I can tackle very soon as this depends on the background HTMLRendering, which is not further developed at the moment and would require me to step in there, when I find time.


Sorry
